# Generated by Django 5.2.12 on 2026-03-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('images', models.JSONField(default=dict)),
                ('description', models.JSONField(default=dict)),
                ('features', models.JSONField(default=list)),
                ('quantity', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=dict)),
            ],
        ),
    ]
